name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls

      - name: Build
        run: echo "Building Application..."

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Application Successfully Deployed"
